# Generated by Django 2.0.6 on 2018-06-19 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.IntegerField(blank=True, default=None, null=True)),
                ('user_sex', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('purpose_of_dating', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('user_smook', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('user_alcogol', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профiль',
                'verbose_name_plural': 'Профiль',
            },
        ),
    ]
